<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-12-18T07:20:49Z" name="Default suite" finished-at="2018-12-18T07:21:31Z" duration-ms="41651">
    <groups>
    </groups>
    <test started-at="2018-12-18T07:20:49Z" name="Default test" finished-at="2018-12-18T07:21:31Z" duration-ms="41651">
      <class name="TestLink">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestLink@60015ef5]" started-at="2018-12-18T07:20:46Z" name="setUp" finished-at="2018-12-18T07:20:49Z" duration-ms="3858" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validTest()[pri:0, instance:TestLink@60015ef5]" started-at="2018-12-18T07:20:50Z" name="validTest" finished-at="2018-12-18T07:21:09Z" duration-ms="19769" status="FAIL">
          <exception class="testlink.api.java.client.TestLinkAPIException">
            <message>
              <![CDATA[The plan SLU Functional Test was not found and the test case SLP-1 could not be accessed to report a test result.]]>
            </message>
            <full-stacktrace>
              <![CDATA[testlink.api.java.client.TestLinkAPIException: The plan SLU Functional Test was not found and the test case SLP-1 could not be accessed to report a test result.
at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:192)
at TestLink.updateTestLinkResult(TestLink.java:116)
at TestLink.validTest(TestLink.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- testlink.api.java.client.TestLinkAPIException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validTest -->
        <test-method signature="invalidTest()[pri:1, instance:TestLink@60015ef5]" started-at="2018-12-18T07:21:09Z" name="invalidTest" finished-at="2018-12-18T07:21:31Z" duration-ms="21842" status="FAIL">
          <exception class="testlink.api.java.client.TestLinkAPIException">
            <message>
              <![CDATA[The plan SLU Functional Test was not found and the test case SLP-2 could not be accessed to report a test result.]]>
            </message>
            <full-stacktrace>
              <![CDATA[testlink.api.java.client.TestLinkAPIException: The plan SLU Functional Test was not found and the test case SLP-2 could not be accessed to report a test result.
at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:192)
at TestLink.updateTestLinkResult(TestLink.java:116)
at TestLink.invalidTest(TestLink.java:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- testlink.api.java.client.TestLinkAPIException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidTest -->
        <test-method is-config="true" signature="close()[pri:0, instance:TestLink@60015ef5]" started-at="2018-12-18T07:21:31Z" name="close" finished-at="2018-12-18T07:21:33Z" duration-ms="1413" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- TestLink -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
